[workspace]
members = [
    "irodori-connection",
    "irodori-security",
    "irodori-core",
    "irodori-proxy",
    "irodori-secure-store",
    "irodori-completion",
    "irodori-connector-abi",
    "irodori-generate",
    "irodori-extension",
]
resolver = "2"

[workspace.package]
version = "0.8.4"
edition = "2021"
license = "0BSD"
authors = ["Irodori Table contributors"]

[workspace.dependencies]
irodori-sql = { git = "https://github.com/irodori-table/irodori-sql", tag = "v0.3.0" }
irodori-error = { git = "https://github.com/irodori-table/irodori-knowledge", tag = "v0.3.2" }
irodori-jobs = { git = "https://github.com/irodori-table/irodori-knowledge", tag = "v0.3.2" }
irodori-knowledge = { git = "https://github.com/irodori-table/irodori-knowledge", tag = "v0.3.2" }
